exp_name: 'resnet34_baseline_bs-128'
outdir: './experiments'

num_gpu: 1
gpu_id: 0

seed: 42

search_for_threshold: True

dataset:
    root: './dataset/shopee-product-matching/'
    path_to_folds: './dataset/shopee-product-matching/folds.csv'
    num_of_classes: 11014
    input_size: 224
    batch_size: 128
    num_workers: 16


model:
    model_name: 'resnet34'
    pretrained: False
    path_to_weights: 'experiments/resnet34_baseline_bs-128/model_resnet34_arcface_val-loss-9.78_epoch-97.pth'
    use_fc: True
    fc_dim: 512
    dropout: 0.5
    loss_module: 'arcface'
    "s": 30.0
    "margin": 0.50
    "ls_eps": 0.0
    "theta_zero": 0.785