exp_name: 'late_fusion'
outdir: './experiments'

num_gpu: 1
gpu_id: 0

seed: 42

search_for_threshold: True
threshold: 0.027
topk: 50

dataset:
    root: './dataset/shopee-product-matching/'
    path_to_folds: './dataset/shopee-product-matching/folds.csv'
    num_of_classes: 11014
    input_size: 224
    batch_size: 32
    num_workers: 16


image_model:
    model_name: 'eca_nfnet_l1'
    pretrained: False
    use_fc: True
    fc_dim: 512
    dropout: 0.
    loss_module: 'arcface'

text_model:
    'model_name': 'cahya/bert-base-indonesian-522M'
    'use_fc': False
    'fc_dim': 512
    'dropout': 0.
    loss_module: 'arcface'

multi:
    'use_fc': True
    'fc_dim': 1920
    'dropout': 0.
    loss_module: 'arcface'

tf_idf:
    max_features: 25000
    binary: True

head:
    "s": 30.0
    "margin": 0.50
    "ls_eps": 0.0
    "theta_zero": 0.785