exp_name: 'tf_idf'
outdir: './experiments'

num_gpu: 1
gpu_id: 0

seed: 42

search_for_threshold: True
threshold: 0.94
topk: 50

dataset:
    root: './dataset/shopee-product-matching/'
    path_to_folds: './dataset/shopee-product-matching/folds.csv'
    num_of_classes: 11014
    input_size: 224
    batch_size: 128
    num_workers: 16


image_model:
    model_name: 'vit_base_patch16_224'
    pretrained: False
    use_fc: True
    fc_dim: 512
    dropout: 0.
    loss_module: 'arcface'
    "s": 30.0
    "margin": 0.50
    "ls_eps": 0.0
    "theta_zero": 0.785

tf_idf:
    max_features: 25000
    binary: True